### ISSUE TITLE
Default config values

### ISSUE THREAD

**Issue by ktsakalozos** [boucherv/charm-keepalived#4]
I was wondering if we could have some sensible default for the virtual ip. In general there is a policy that charms deploy out of the box without any configuration needed.

Also is the ens interface safe? Will it be there in all deployments? We could we have as interface value "auto" and try to autodetect the proper one. If the user configures the charm with something other than "auto" we use what the user configured. If we fail a proper interface we block until the user provides one. In the zookeeper charm we are trying to be smart: https://github.com/juju-solutions/layer-apache-zookeeper/blob/7a6aa6d1dfa7af8b4ad6b4f236b9ce0df478c571/lib/charms/layer/zookeeper.py#L22 There is also methods in charm helpers that list the available interfaces.

**Comment by boucherv** [comment]
Yes you are right

I updated the charm with a default network interface automatic config same as the flannel charm!

For the virtual ip default config I think we can't do the same. The user must set the virtual ip parameter
