### ISSUE TITLE
Minor metadata fixes

### ISSUE THREAD

**Issue by ktsakalozos** [boucherv/charm-keepalived#6]
Could you please update the maintainers list and the repo field?

Thanks

**Comment by boucherv** [comment]
Yes for sure! Done, it's fine ? https://github.com/boucherv/charm-keepalived/commit/4ffe33def1c65ce62c67005f2ebf77880e13c275

**Comment by ktsakalozos** [comment]
Thank you for adding me as a maintainer. I appreciate that.
