### ISSUE TITLE
Installation instructions incomplete (lacking relation)

### ISSUE THREAD

**Issue by vvangestel** [boucherv/charm-keepalived#7]
Following the installation instructions for kubernetes, the application didn't get deployed.
An important relation wasn't automatically added to the model.
`juju add-relation keepalived:juju-info kubeapi-load-balancer:juju-info` fixed the issue and should be added to the instructions.

**Comment by boucherv** [comment]
Hi  @vvangestel,

Thanks for this feedback. I put directly keepalived in the kubernetes bundle in order to deploy it so I don't catch this issue.

The 'juju add-relation kubeapi-load-balancer keepalived' don't solve this issue you must specify the juju-info ?

Thanks in advance,
Valentin

**Comment by vvangestel** [comment]
After running the original installation instructions first...
```bash
$ juju add-relation kubeapi-load-balancer keepalived
cannot add relation "kubeapi-load-balancer:apiserver keepalived:website": relation kubeapi-load-balancer:apiserver keepalived:website already exists (already exists)
```
It seems without specifying the exact relation, juju prefers the incorrect one and doesn't add the `juju-info` type on its own.

**Comment by vvangestel** [comment]
Not sure if related, but the kubeapi-loadbalancer didn't seem to be correctly configured either. Kubelet and the kube client both complain that the VIP:443 isn't accepting connections.
An nmap of the VIP and the different masters also only shows port 22 and 80 to be open.
Do I have the correct relations setup in the first place?
```
- - keepalived:juju-info
  - kubeapi-load-balancer:juju-info
- - kubeapi-load-balancer:apiserver
  - keepalived:website
- - keepalived:website
  - kubernetes-worker:kube-api-endpoint
- - keepalived:loadbalancer
  - kubernetes-master:loadbalancer
```
The meaning of the relations aren't very clear to me, but that is an issue I have with Juju charms in general ;)

*Edit* It seems the `kubeapi-load-balancer:apiserver keepalived:website` relation shouldn't be there, but is chosen by default with `juju add-relation kubeapi-load-balancer keepalived`.

**Comment by vvangestel** [comment]
I also had to manually add the VIP as an extra SAN to the kubeapi-loadbalancer, otherwise connections were immediately refused due to the certificate not being valid. Should this be a manual step, or should this be configured automatically by the charm?

**Comment by boucherv** [comment]
Hi @vvangestel,

Thanks for your relation issue, I will fix that!

Yes .. you must do that manually because this is in the kubeapi-loadbalancer charm and I prefer to keep the upstream charm so .. But by using a bundle it's really easy to do that - [kubernetes_bundles_with_keepalived.zip](https://github.com/boucherv/charm-keepalived/files/2115118/kubernetes_bundles_with_keepalived.zip)

**Comment by vvangestel** [comment]
True, though it might be nice for future users to know in advance that their certificates should be updated to allow the VIP. The logs of the kubernetes-worker are fairly straightforward, but it still requires people to actually read the logs ;)

Anyway, it all seems to be working fine now!
